name: 'dbt_snowflake_listings_integration_tests'
version: '0.2.3'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

vars:
  integration_listing_name: TEST_ORG_LISTING
  integration_share_name: DBT_MARKETPLACE_TEST_SHARE

models:
  dbt_snowflake_listings_integration_tests:
    staging:
      +materialized: table
      +transient: true
    listings:
      +materialized: organization_listing
