name: 'snowflake_sample_data_listing_example'
version: '0.2.2'
config-version: 2

profile: 'example'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  snowflake_sample_data_listing_example:
    staging:
      +materialized: table
      +transient: true
    listings:
      +materialized: organization_listing
